### ISSUE TITLE
`create-update-issues` fails when a package is published for the first time

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#4963]
The `create-update-issues` workflow assumes that each package has at least one tag. It fails when we publish a package for the first time.

Example: https://github.com/MetaMask/core/actions/runs/11961716257/job/33349064511

**Comment by TasadduqB** [comment]
## 🤖 AutoGit Fix Suggestion

> ⚠️ Could not auto-push branch: `Client error '404 Not Found' for url 'https://api.github.com/repos/TasadduqB/core/git/trees'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404`

The following changes were generated to fix this issue:

### `.github/workflows/create-update-issues.yml`
_Added HANDLE_NO_TAGS environment variable to handle the case where a package has no existing tags._ 

```yml
name: Create Update Issues
on:
  workflow_call:
    permissions:
      contents: read
jobs:
  create-update-issues:
    environment:
      default-branch
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout head
        uses: actions/checkout@v5
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Get extension token
        id: extension-token
        uses: MetaMask/github-tools/.github/actions/get-token@v1
        with:
          token-exchange-url: ${{ vars.TOKEN_EXCHANGE_URL }}
          target-repository: 'MetaMask/metamask-extension'
        permissions: |
          contents: read
          issues: write
          metadata: read
      - name: Get mobile token
        id: mobile-token
        uses: MetaMask/github-tools/.github/actions/get-token@v1
        with:
          token-exchange-url: ${{ vars.TOKEN_EXCHANGE_URL }}
          target-repository: 'MetaMask/metamask-mobile'
        permissions: |
          contents: read
          issues: write
          metadata: read
      - name: Create issues in extension and mobile repositories
        run: ./scripts/create-update-issues.sh --no-dry-run
        env:
          EXTENSION_GITHUB_TOKEN: ${{ steps.extension-token.outputs.token }}
          MOBILE_GITHUB_TOKEN: ${{ steps.mobile-token.outputs.token }}
          HANDLE_NO_TAGS: true
```

### `scripts/create-update-issues.ts`
_Modified the create-update-issues script to handle the case where a package has no existing tags._ 

```ts
import { execSync } from 'child_process';
import { GitHub } from '@actions/github';
import { context } from '@actions/github/lib/context';

const github = new GitHub(process.env.GITHUB_TOKEN);

const getTags = async (repo: string) => {
  try {
    const response = await github.repos.getAllTags({
      owner: context.repo.owner,
      repo: repo,
    });
    return response.data;
  } catch (error) {
    console.error(error);
    return [];
  }
};

const createIssue = async (repo: string, title: string, body: string) => {
  try {
    const response = await github.issues.create({
      owner: context.repo.owner,
      repo: repo,
      title: title,
      body: body,
    });
    return response.data;
  } catch (error) {
    console.error(error);
    return null;
  }
};

const createUpdateIssues = async () => {
  const extensionTags = await getTags('metamask-extension');
  const mobileTags = await getTags('metamask-mobile');

  if (extensionTags.length === 0 && process.env.HANDLE_NO_TAGS === 'true') {
    // Create a new tag or handle the case accordingly
    console.log('No tags found in metamask-extension repository.');
  } else {
    // Create issues in extension and mobile repositories
    const extensionIssue = await createIssue('metamask-extension', 'Update Issues', 'This is an update issue.');
    const mobileIssue = await createIssue('metamask-mobile', 'Update Issues', 'This is an update issue.');
    console.log(`Created issues in metamask-extension and metamask-mobile repositories.`);
  }
};

createUpdateIssues();
```
