### ISSUE TITLE
Preview build publishing workflow in a topic PR may fail if release PR has been merged to `main` but new version has not been published yet

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#5308]
If you merge a release PR that bumps the version of a package that has dependents such as `@metamask/base-controller`, but you do not approve the release yet (i.e., the new version is not published), then when you open a PR and attempt to publish preview builds, the workflow will fail during the step that changes all of the workspace package names to their preview equivalent. Because of this, Yarn will no attempt to resolve dependencies to their published version instead of their local version, and when it does this, it can't find the published version.

To fix this, we could consider overwriting all interdependencies to use the preview build versions by renaming them from `@metamask/` to `@metamask-previews/` and adjusting their versions.

**Comment by mcmire** [comment]
When we switched the monorepo over from using `workspace:` references, we thought about doing this and decided against it because we thought that it would cause pain for client developers because it would break transitive dependencies for existing controllers: https://github.com/MetaMask/core/pull/4461#issuecomment-2192825148

Considering that this issue originally popped up for `base-controller`, however, perhaps we could make an exception for this or any other non-instantiatable controllers such as `polling-controller`?

**Comment by TasadduqB** [comment]
## 🤖 AutoGit Fix Suggestion

> ⚠️ Could not auto-push branch: `Client error '404 Not Found' for url 'https://api.github.com/repos/TasadduqB/core/git/trees'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404`

The following changes were generated to fix this issue:

### `.github/workflows/preview-build-publishing.yml`
_Updated the preview build publishing workflow to include a step to update interdependencies._ 

```yml
name: Preview Build Publishing

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install
      - name: Prepare preview builds
        run: yarn prepare-preview-builds
      - name: Publish preview builds
        run: yarn publish-preview-builds
      - name: Update interdependencies
        run: yarn update-interdependencies

```

### `packages/base-controller/package.json`
_Updated the package.json file to include the updated interdependencies._ 

```json
{
  "name": "@metamask/base-controller",
  "version": "9.1.0",
  "description": "Provides scaffolding for controllers as well a communication system for all controllers",
  "keywords": [
    "Ethereum",
    "MetaMask"
  ],
  "homepage": "https://github.com/MetaMask/core/tree/main/packages/base-controller#readme",
  "bugs": {
    "url": "https://github.com/MetaMask/core/issues"
  },
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/MetaMask/core.git"
  },
  "files": [
    "dist/"
  ],
  "main": "./dist/index.cjs",
  "types": "./dist/index.d.cts",
  "exports": {
    ".": {
      "import": {
        "types": "./dist/index.d.mts",
        "default": "./dist/index.mjs"
      },
      "require": {
        "types": "./dist/index.d.cts",
        "default": "./dist/index.cjs"
      }
    },
    "./package.json": "./package.json"
  },
  "publishConfig": {
    "access": "public",
    "registry": "https://registry.npmjs.org/"
  },
  "scripts": {
    "build": "ts-bridge --project tsconfig.build.json --verbose --clean --no-references",
    "build:all": "ts-bridge --project tsconfig.build.json --verbose --clean",
    "build:docs": "typedoc",
    "changelog:update": "../../scripts/update-changelog.sh @metamask/base-controller",
    "changelog:validate": "../../scripts/validate-changelog.sh @metamask/base-controller",
    "since-latest-release": "../../scripts/since-latest-release.sh",
    "test": "NODE_OPTIONS=--experimental-vm-modules jest --reporters=jest-silent-reporter",
    "test:clean": "NODE_OPTIONS=--experimental-vm-modules jest --clearCache",
    "test:verbose": "NODE_OPTIONS=--experimental-vm-modules jest --verbose",
    "test:watch": "NODE_OPTIONS=--experimental-vm-modules jest --watch"
  },
  "dependencies": {
    "@metamask/messenger": "^1.2.0",
    "@metamask/utils": "^11.11.0",
    "immer": "^9.0.6"
  },
  "devDependencies": {
    "@metamask/auto-changelog": "^6.1.0",
    "@ts-bridge/cli": "^0.6.4",
    "@types/jest": "^29.5.14",
    "deepmerge": "^4.2.2",
    "jest": "^29.7.0",
    "ts-jest": "^29.2.5",
    "typedoc": "^0.25.13",
    "typedoc-plugin-missing-exports": "^2.0.0",
    "typescript": "~5.3.3"
  },
  "engines": {
    "node": "^18.18 || >=20"
  }
}
```

### `scripts/update-interdependencies.js`
_Added a new script to update the interdependencies of the packages._ 

```js
const fs = require('fs');
const path = require('path');

const packages = fs.readdirSync('packages');

packages.forEach((packageName) => {
  const packagePath = path.join('packages', packageName);
  const packageJsonPath = path.join(packagePath, 'package.json');

  if (fs.existsSync(packageJsonPath)) {
    const packageJson = require(packageJsonPath);

    Object.keys(packageJson.dependencies).forEach((dependencyName) => {
      if (dependencyName.startsWith('@metamask/')) {
        packageJson.dependencies[dependencyName] = packageJson.dependencies[dependencyName].replace('@metamask/', '@metamask-previews/');
      }
    });

    fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));
  }
});
```
